[package]
name = "bindery"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
fastrace.workspace = true
gpui.workspace = true

